---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rscale/ubuntu-cf
    tag: 'latest'

inputs:
  - name: rc-app
  - name: rc-manifest
  - name: ci

run:
  path: ci/ci/tasks/integration-test.sh

params:
  CF_API:
  CF_USERNAME:
  CF_PASSWORD:
  CF_ORG:
  CF_SPACE:
  CF_ROUTE:
  CF_SERVICE:
  CF_PLAN: